import { RACE_ENUM } from "./race"

export const FETCH_PLACE = "FETCH_PLACE"
export const REQUEST = "REQUEST"

export const FETCH_SETTLEMENTS = "FETCH_SETTLEMENTS"
export const RECEIVE_SETTLEMENT = "RECEIVE_SETTLEMENT"
export const RECEIVE_SETTLEMENTS = "RECEIVE_SETTLEMENTS"

export const FETCH_PEOPLE = "FETCH_PEOPLE"
export const RECEIVE_PEOPLE = "RECEIVE_PEOPLE"

export const FETCH_RELATIONS = "FETCH_RELATIONS"
export const RECEIVE_RELATIONS = "RECEIVE_RELATIONS"

export const FETCH_RELATION_TYPES = "FETCH_RELATION_TYPES"
export const RECEIVE_RELATION_TYPES = "RECEIVE_RELATION_TYPES"

export const RACE = RACE_ENUM
