export const FETCH_PLACE = "FETCH_PLACE"

export const FETCH_SETTLEMENTS = "FETCH_SETTLEMENTS"
export const RECEIVE_SETTLEMENTS = "RECEIVE_SETTLEMENTS"

export const FETCH_PEOPLE = "FETCH_PEOPLE"
export const RECEIVE_PEOPLE = "RECEIVE_PEOPLE"
